"""empty message

Revision ID: 0b71ea6500cf
Revises: c985a1641a24
Create Date: 2020-11-05 22:41:44.360072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b71ea6500cf'
down_revision = 'c985a1641a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'rating')
    # ### end Alembic commands ###
